### PyTorch Introduction

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU Exists:", torch.cuda.get_device_name())

GPU Exists: NVIDIA GeForce RTX 5070


### Creating a Tensor

In [ ]:
# Empty
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# Random
torch.rand(2,3)

tensor([[0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742]])

In [ ]:
# Setting Seed to get same matrix values for reproducibility.

torch.manual_seed(0)
x = torch.rand(2,3)

torch.manual_seed(0)
y = torch.rand(2,3)

x==y

tensor([[True, True, True],
        [True, True, True]])

In [20]:
# Torch from List

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# Arange
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [24]:
# Even Spacing
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
# Identity Matrix
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [29]:
# Full
torch.full((2,3), 47)

tensor([[47, 47, 47],
        [47, 47, 47]])

### Tensor Shapes

In [32]:
x = torch.empty(2,8)
print(x)
print(x.shape)

tensor([[3.9839e-19, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00]])
torch.Size([2, 8])


In [34]:
x = torch.empty(2,8)
print(x)
print(x.size())

tensor([[3.9839e-19, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00]])
torch.Size([2, 8])


In [ ]:
# Create Same Shape Tensors
y = torch.empty_like(x)
print(y)
print(y.shape)

tensor([[3.9847e-19, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00]])
torch.Size([2, 8])


In [38]:
z = torch.zeros_like(x)
print(z)
print(z.shape)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([2, 8])


In [39]:
zz = torch.ones_like(x)
print(zz)
print(zz.shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([2, 8])


In [40]:
zzz = torch.rand_like(x)
print(zzz)
print(zzz.shape)

tensor([[0.4901, 0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816, 0.9152]])
torch.Size([2, 8])


In [45]:
zzz = torch.rand_like(x)
print(zzz)
print(zzz.shape)

tensor([[0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362, 0.1852, 0.3734],
        [0.3051, 0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298]])
torch.Size([2, 8])


### Tensor Data Types

In [46]:
x.dtype

torch.float32

In [49]:
# Create Int type Tensor
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [50]:
torch.tensor([1,2,3,4], dtype=torch.float16)

tensor([1., 2., 3., 4.], dtype=torch.float16)

In [51]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int8)

tensor([1, 2, 3], dtype=torch.int8)

In [ ]:
# Change Data Type of existing tensor
x = 12 + torch.rand(2,2)
print(x.dtype)
print(x)

y = x.to(torch.int8)
print(y.dtype)
print(y)

torch.float32
tensor([[12.8352, 12.2056],
        [12.5932, 12.1123]])
torch.int8
tensor([[12, 12],
        [12, 12]], dtype=torch.int8)
