### PyTorch nn Module

In last notebook, we created the Neural Network training pipeline and used raw code, now we'll use some PyTorch functionality to improve that.

We'll make following improvements:
1. Building Neural Network using nn module.
2. Use built-in activation function.
3. Use built-in loss function.
4. Use built-in optimizer

torch.nn Module (Build Neural Networks efficiently. It'll provide use pre-built layers, activation functions and loss functions.)

In [1]:
import torch
import torch.nn as nn
import pandas as pd

In [2]:
class SimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [3]:
# Create Dataset
features = torch.rand(10, 5, dtype=torch.float32)

# Create Model
model = SimpleNN(features.shape[1])

# Forward Pass
model(features)

tensor([[0.7170],
        [0.6693],
        [0.6224],
        [0.7081],
        [0.6129],
        [0.5837],
        [0.6536],
        [0.7095],
        [0.5792],
        [0.6367]], grad_fn=<SigmoidBackward0>)

In [4]:
# Show Model Weights
model.linear.weight

Parameter containing:
tensor([[0.3814, 0.0347, 0.3951, 0.1780, 0.0381]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.0556], requires_grad=True)

In [6]:
# Using torchinfo to see Neural Network Summary
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
SimpleNN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [7]:
# Lets create a Neural Network with Hidden Layer
class HLNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out


In [8]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = HLNN(features.shape[1])

# Forward Pass
model(features)

tensor([[0.3047],
        [0.3397],
        [0.2860],
        [0.2638],
        [0.2633],
        [0.3317],
        [0.2976],
        [0.3044],
        [0.2879],
        [0.3568]], grad_fn=<SigmoidBackward0>)

In [9]:
# Model Summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
HLNN                                     [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:
# Using Sequential Container
class SeqHLNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        return self.network(features)

In [11]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = SeqHLNN(features.shape[1])

# Forward Pass
model(features)

tensor([[0.5662],
        [0.5841],
        [0.5782],
        [0.5512],
        [0.5805],
        [0.5953],
        [0.5594],
        [0.5523],
        [0.5854],
        [0.5788]], grad_fn=<SigmoidBackward0>)

In [12]:
# Model Summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
SeqHLNN                                  [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
# Now using what we have learned, we apply it to same dataset which we used in previous notebook.

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.drop(["id", "Unnamed: 32"], axis=1, inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [14]:
# Train Test Split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(df.drop(["diagnosis"], axis=1), df["diagnosis"], test_size=0.2, random_state=42)
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]], shape=(455, 30))

In [15]:
from sklearn.preprocessing import LabelEncoder

# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [16]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [17]:
# Move from Numpy Arrays to PyTorch Tensors
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

X_train_tensor = torch.from_numpy(X_train).to(device=device, dtype=torch.float32)
X_test_tensor = torch.from_numpy(X_test).to(device=device, dtype=torch.float32)
y_train_tensor = torch.from_numpy(y_train).to(device=device, dtype=torch.float32)
y_test_tensor = torch.from_numpy(y_test).to(device=device, dtype=torch.float32)


In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [19]:
X_train_tensor


tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       device='cuda:0')

In [20]:
y_train_tensor.shape

torch.Size([455])

In [21]:
y_train_tensor

tensor([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
        0., 1., 1., 0., 1., 1., 0., 0., 

In [22]:
# Model Class

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, X):
        out = self.linear(X)
        out = self.sigmoid(out)
        return out

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss 


In [23]:
# Create Model

learning_rate = 0.1
epochs = 25
model = Model(X_train_tensor.shape[1])
model = model.to(device=device)

# Define Loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model(X_train_tensor)

    # Compute Loss
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward Pass
    loss.backward()

    # Update Parameters
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # Zero Gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # Print Loss Function
    print(f"Epoch: {epoch}, Loss: {loss}")


Epoch: 0, Loss: 0.7268898487091064
Epoch: 1, Loss: 0.7071666121482849
Epoch: 2, Loss: 0.695110023021698
Epoch: 3, Loss: 0.6878085732460022
Epoch: 4, Loss: 0.6833041310310364
Epoch: 5, Loss: 0.6803956627845764
Epoch: 6, Loss: 0.6783925890922546
Epoch: 7, Loss: 0.6769131422042847
Epoch: 8, Loss: 0.6757485866546631
Epoch: 9, Loss: 0.6747843027114868
Epoch: 10, Loss: 0.6739557385444641
Epoch: 11, Loss: 0.6732246279716492
Epoch: 12, Loss: 0.6725672483444214
Epoch: 13, Loss: 0.6719682216644287
Epoch: 14, Loss: 0.6714169383049011
Epoch: 15, Loss: 0.6709057092666626
Epoch: 16, Loss: 0.670428991317749
Epoch: 17, Loss: 0.6699824929237366
Epoch: 18, Loss: 0.6695627570152283
Epoch: 19, Loss: 0.6691671013832092
Epoch: 20, Loss: 0.6687932014465332
Epoch: 21, Loss: 0.6684393286705017
Epoch: 22, Loss: 0.6681039333343506
Epoch: 23, Loss: 0.6677857041358948
Epoch: 24, Loss: 0.6674833297729492


In [24]:
model.linear.weight

Parameter containing:
tensor([[-0.1043,  0.0426, -0.1041, -0.0425,  0.1104, -0.0343,  0.0750, -0.0794,
         -0.0930, -0.1719, -0.0261,  0.0664, -0.0104, -0.0015, -0.1528,  0.0929,
          0.0071, -0.0102,  0.0538,  0.0630,  0.0099, -0.0960,  0.0601,  0.2095,
          0.0673,  0.0227, -0.1263,  0.0237, -0.0583,  0.1382]],
       device='cuda:0', requires_grad=True)

In [25]:
model.linear.bias

Parameter containing:
tensor([-0.3351], device='cuda:0', requires_grad=True)

In [26]:
# Evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy}")

Accuracy: 0.6141889691352844


In [27]:
# We improved 2 things till now out of four:
# We are now using builtin nn Module
# We are now using builtin Activation Function
# Now two improvements are remaining - Built-in Activation Function and Built-in Optimizer.

In [28]:
# Modified Model Class

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        out = self.linear(X)
        out = self.sigmoid(out)
        return out

loss_function = nn.BCELoss()

In [29]:
# Create Model

learning_rate = 0.1
epochs = 25
model = Model(X_train_tensor.shape[1])
model = model.to(device=device)

# Define Loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model(X_train_tensor)

    # Compute Loss
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # Backward Pass
    loss.backward()

    # Update Parameters
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # Zero Gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # Print Loss Function
    print(f"Epoch: {epoch}, Loss: {loss}")


Epoch: 0, Loss: 0.7176156640052795
Epoch: 1, Loss: 0.5514902472496033
Epoch: 2, Loss: 0.459989458322525
Epoch: 3, Loss: 0.40247076749801636
Epoch: 4, Loss: 0.36262330412864685
Epoch: 5, Loss: 0.33311185240745544
Epoch: 6, Loss: 0.31019240617752075
Epoch: 7, Loss: 0.29175591468811035
Epoch: 8, Loss: 0.2765214741230011
Epoch: 9, Loss: 0.2636643946170807
Epoch: 10, Loss: 0.2526281177997589
Epoch: 11, Loss: 0.24302226305007935
Epoch: 12, Loss: 0.2345644235610962
Epoch: 13, Loss: 0.22704455256462097
Epoch: 14, Loss: 0.2203027904033661
Epoch: 15, Loss: 0.21421502530574799
Epoch: 16, Loss: 0.20868335664272308
Epoch: 17, Loss: 0.20362913608551025
Epoch: 18, Loss: 0.19898851215839386
Epoch: 19, Loss: 0.19470898807048798
Epoch: 20, Loss: 0.19074684381484985
Epoch: 21, Loss: 0.18706545233726501
Epoch: 22, Loss: 0.18363380432128906
Epoch: 23, Loss: 0.18042539060115814
Epoch: 24, Loss: 0.17741753160953522


In [30]:
# Evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy}")

Accuracy: 0.5301631093025208


In [31]:
# Now we improved by adding Built-in Loss function
# Last modification remaining is to use built-in optimizer (We are going to use torch.optim for that.)

# torch.optim is module in PyTorch that provides variety of optimization algorithms.
# Some common are Stochastic GD, Adam, RMSprop

In [32]:
# Final Model (All 4 improvements)

class FModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(num_features, 1),
            nn.Sigmoid()
        )
    
    def forward(self, X):
        return self.layers(X)

model = FModel(X_train_tensor.shape[1])
model = model.to(device=device)

learning_rate = 0.1
epochs = 25

# Define Loss Function
loss_function = nn.BCELoss()

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [33]:
# Define Loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model(X_train_tensor)

    # Compute Loss
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # Zero Gradients
    optimizer.zero_grad()

    # Backward Pass
    loss.backward()

    # Update Parameters
    optimizer.step()

    # Print Loss Function
    print(f"Epoch: {epoch}, Loss: {loss}")


Epoch: 0, Loss: 0.5956408977508545
Epoch: 1, Loss: 0.4961598813533783
Epoch: 2, Loss: 0.4344728887081146
Epoch: 3, Loss: 0.3915950357913971
Epoch: 4, Loss: 0.3596024215221405
Epoch: 5, Loss: 0.3345688581466675
Epoch: 6, Loss: 0.31429874897003174
Epoch: 7, Loss: 0.2974568009376526
Epoch: 8, Loss: 0.28317898511886597
Epoch: 9, Loss: 0.27087870240211487
Epoch: 10, Loss: 0.2601420283317566
Epoch: 11, Loss: 0.25066763162612915
Epoch: 12, Loss: 0.24222996830940247
Epoch: 13, Loss: 0.23465655744075775
Epoch: 14, Loss: 0.2278127521276474
Epoch: 15, Loss: 0.22159169614315033
Epoch: 16, Loss: 0.21590714156627655
Epoch: 17, Loss: 0.21068881452083588
Epoch: 18, Loss: 0.20587846636772156
Epoch: 19, Loss: 0.20142756402492523
Epoch: 20, Loss: 0.1972951591014862
Epoch: 21, Loss: 0.19344642758369446
Epoch: 22, Loss: 0.1898515671491623
Epoch: 23, Loss: 0.1864849478006363
Epoch: 24, Loss: 0.18332424759864807


In [34]:
# Evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy}")

Accuracy: 0.5280085802078247


In [35]:
# We have made all the improvements.