### PyTorch Introduction

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU Exists:", torch.cuda.get_device_name())

GPU Exists: NVIDIA GeForce RTX 5070


### Creating a Tensor

In [3]:
# Empty
torch.empty(2,3)

tensor([[6.1523e+03, 4.0837e-41, 6.1523e+03],
        [4.0837e-41, 1.5085e-21, 0.0000e+00]])

In [4]:
# Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# Random
torch.rand(2,3)

tensor([[0.6875, 0.4867, 0.4758],
        [0.8025, 0.3593, 0.1818]])

In [7]:
# Setting Seed to get same matrix values for reproducibility.

torch.manual_seed(0)
x = torch.rand(2,3)

torch.manual_seed(0)
y = torch.rand(2,3)

x==y

tensor([[True, True, True],
        [True, True, True]])

In [8]:
# Torch from List

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# Arange
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [10]:
# Even Spacing
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
# Identity Matrix
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [12]:
# Full
torch.full((2,3), 47)

tensor([[47, 47, 47],
        [47, 47, 47]])

### Tensor Shapes

In [13]:
x = torch.empty(2,8)
print(x)
print(x.shape)

tensor([[1.6582e-40, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00]])
torch.Size([2, 8])


In [14]:
x = torch.empty(2,8)
print(x)
print(x.size())

tensor([[1.4960e-21, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00]])
torch.Size([2, 8])


In [15]:
# Create Same Shape Tensors
y = torch.empty_like(x)
print(y)
print(y.shape)

tensor([[1.4961e-21, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00]])
torch.Size([2, 8])


In [16]:
z = torch.zeros_like(x)
print(z)
print(z.shape)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([2, 8])


In [17]:
zz = torch.ones_like(x)
print(zz)
print(zz.shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([2, 8])


In [18]:
zzz = torch.rand_like(x)
print(zzz)
print(zzz.shape)

tensor([[0.4901, 0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816, 0.9152]])
torch.Size([2, 8])


In [19]:
zzz = torch.rand_like(x)
print(zzz)
print(zzz.shape)

tensor([[0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362, 0.1852, 0.3734],
        [0.3051, 0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298]])
torch.Size([2, 8])


### Tensor Data Types

In [20]:
x.dtype

torch.float32

In [21]:
# Create Int type Tensor
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3,4], dtype=torch.float16)

tensor([1., 2., 3., 4.], dtype=torch.float16)

In [23]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int8)

tensor([1, 2, 3], dtype=torch.int8)

In [24]:
# Change Data Type of existing tensor
x = 12 + torch.rand(2,2)
print(x.dtype)
print(x)

y = x.to(torch.int8)
print(y.dtype)
print(y)

torch.float32
tensor([[12.7231, 12.7423],
        [12.5263, 12.2437]])
torch.int8
tensor([[12, 12],
        [12, 12]], dtype=torch.int8)


### Mathematical Operations

In [25]:
x = torch.rand(2,3)
print(x)

tensor([[0.5846, 0.0332, 0.1387],
        [0.2422, 0.8155, 0.7932]])


#### 1. Scalar Operations

In [26]:
print(x)

# addition
print(x+2)

# substraction
print(x-2)

# multiplication
print(x*10)

# division
print(x/0.10)

# int division
print(x*100//3)

# mod
print(x*100%3)

# power
print(x**10)

# abs
print((x-2).abs())

tensor([[0.5846, 0.0332, 0.1387],
        [0.2422, 0.8155, 0.7932]])
tensor([[2.5846, 2.0332, 2.1387],
        [2.2422, 2.8155, 2.7932]])
tensor([[-1.4154, -1.9668, -1.8613],
        [-1.7578, -1.1845, -1.2068]])
tensor([[5.8459, 0.3315, 1.3872],
        [2.4223, 8.1547, 7.9316]])
tensor([[5.8459, 0.3315, 1.3872],
        [2.4223, 8.1547, 7.9316]])
tensor([[19.,  1.,  4.],
        [ 8., 27., 26.]])
tensor([[1.4592, 0.3153, 1.8717],
        [0.2235, 0.5469, 1.3161]])
tensor([[4.6616e-03, 1.6039e-15, 2.6381e-09],
        [6.9562e-07, 1.3004e-01, 9.8540e-02]])
tensor([[1.4154, 1.9668, 1.8613],
        [1.7578, 1.1845, 1.2068]])


#### 2. Element wise operations

In [27]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print("a:\n", a)
print("b:\n", b)

a:
 tensor([[0.2783, 0.4820, 0.8198],
        [0.9971, 0.6984, 0.5675]])
b:
 tensor([[0.8352, 0.2056, 0.5932],
        [0.1123, 0.1535, 0.2417]])


In [28]:
# add
print("a+b:\n", a+b)

# sub
print("a-b:\n", a-b)

# mul
print("a*b:\n", a*b)

# divide
print("a/b:\n", a/b)

# power
print("a**b:\n", a**b)

# mod
print("a%b:\n", a%b)

a+b:
 tensor([[1.1135, 0.6876, 1.4130],
        [1.1094, 0.8519, 0.8093]])
a-b:
 tensor([[-0.5570,  0.2764,  0.2266],
        [ 0.8847,  0.5450,  0.3258]])
a*b:
 tensor([[0.2324, 0.0991, 0.4863],
        [0.1120, 0.1072, 0.1372]])
a/b:
 tensor([[0.3331, 2.3442, 1.3820],
        [8.8749, 4.5514, 2.3481]])
a**b:
 tensor([[0.3435, 0.8607, 0.8888],
        [0.9997, 0.9464, 0.8720]])
a%b:
 tensor([[0.2783, 0.0708, 0.2266],
        [0.0983, 0.0846, 0.0841]])


In [29]:
# Absolute value
x = torch.randint(-100, 100, (2,3))
print(x)

abs_x = x.abs()
print(abs_x)

tensor([[ -1,  26,  63],
        [-26,  75,   0]])
tensor([[ 1, 26, 63],
        [26, 75,  0]])


In [30]:
# Negative
neg_x = torch.neg(x)
print(neg_x)

tensor([[  1, -26, -63],
        [ 26, -75,   0]])


In [31]:
# Round
x = torch.randint(-100, 100, (2,3)) + torch.rand(2,3)
print(x)
torch.round(x)

tensor([[-81.3035, -67.0857,  68.9351],
        [-87.0588, -22.4005, -54.9348]])


tensor([[-81., -67.,  69.],
        [-87., -22., -55.]])

In [32]:
# ceil
torch.ceil(x)

tensor([[-81., -67.,  69.],
        [-87., -22., -54.]])

In [33]:
# floor
torch.floor(x)

tensor([[-82., -68.,  68.],
        [-88., -23., -55.]])

In [34]:
# clamping
torch.clamp(x , min=-50, max=50)

tensor([[-50.0000, -50.0000,  50.0000],
        [-50.0000, -22.4005, -50.0000]])

#### 3. Reduction Operations

In [35]:
e = torch.randint(-100, 100, (2,3), dtype=torch.float32)
print(e)

tensor([[-19., -10., -18.],
        [ 19.,  44., -67.]])


In [36]:
# Sum
torch.sum(e)

tensor(-51.)

In [37]:
# Sum along dimensions
# Along Columns
print(torch.sum(e, dim=0))

# Along Rows
print(torch.sum(e, dim=1))

tensor([  0.,  34., -85.])
tensor([-47.,  -4.])


In [38]:
# Mean
torch.mean(e)

tensor(-8.5000)

In [39]:
# Median
torch.median(e)

tensor(-18.)

In [40]:
# Max & Min
torch.max(e), torch.min(e)

(tensor(44.), tensor(-67.))

In [41]:
# Product 
torch.prod(e)

tensor(1.9156e+08)

In [42]:
# Standard Deviation, Variance
torch.std(e), torch.var(e)

(tensor(37.7823), tensor(1427.5000))

In [43]:
# argmax
torch.argmax(e)

tensor(4)

In [44]:
# argmin
torch.argmin(e)

tensor(5)

#### 4. Matrix Operations

In [45]:
p = torch.randint(-10, 10, (3,4), dtype=torch.float32) + torch.rand(3, 4, dtype=torch.float32)
q = torch.randint(-10, 10, (4,3), dtype=torch.float32) + torch.rand(4, 3, dtype=torch.float32)

print("p:\n", p)
print("q:\n", q)

p:
 tensor([[-0.2503, -6.3953, -0.8900,  3.2121],
        [ 9.9704,  8.8369,  5.2820, -6.6258],
        [-7.9763,  8.4910,  5.1235,  6.1143]])
q:
 tensor([[-2.3038, -1.4700,  5.2560],
        [-5.2634, -5.9796, -1.7964],
        [-5.6252,  4.2564,  9.3251],
        [-9.9098, -2.6064,  4.6069]])


In [46]:
# Matrix Multiplication
print("p@q:\n", torch.matmul(p, q))
print("p@q:\n", p@q)

p@q:
 tensor([[   7.4135,   26.4495,   16.6705],
        [ -33.5330,  -27.7465,   55.2610],
        [-115.7281,  -33.1759,   18.7682]])
p@q:
 tensor([[   7.4135,   26.4495,   16.6705],
        [ -33.5330,  -27.7465,   55.2610],
        [-115.7281,  -33.1759,   18.7682]])


In [47]:
# Dot product
v1 = torch.tensor([1,2])
v2 = torch.tensor([4,5])

torch.dot(v1, v2)

tensor(14)

In [48]:
# Transpose
torch.transpose(p, 0, 1)

tensor([[-0.2503,  9.9704, -7.9763],
        [-6.3953,  8.8369,  8.4910],
        [-0.8900,  5.2820,  5.1235],
        [ 3.2121, -6.6258,  6.1143]])

In [49]:
# Determinant
torch.det(p@q)

tensor(-177758.5625)

In [50]:
# Inverse
torch.inverse(p@q)

tensor([[-0.0074,  0.0059, -0.0108],
        [ 0.0324, -0.0116,  0.0054],
        [ 0.0118,  0.0158, -0.0038]])

In [51]:
# Test Inverse
torch.round(p@q@(torch.inverse(p@q)))

tensor([[1., 0., 0.],
        [0., 1., -0.],
        [0., 0., 1.]])

#### 5. Comparison Operations

In [52]:
i, j = [torch.randint(-20, 20, (2,2)) for i in range(2)]
print("i:\n", i)
print("j:\n", j)

i:
 tensor([[ 17,  18],
        [  4, -19]])
j:
 tensor([[-10, -16],
        [-10,   4]])


In [53]:
# greater than
print(i > j)

# less than
print(i < j)

# Equal to
print(i == j)

# not equal to
print(i != j)

# greater than equal to
print(i >= j)

# less than equal to
print(i <= j)

tensor([[ True,  True],
        [ True, False]])
tensor([[False, False],
        [False,  True]])
tensor([[False, False],
        [False, False]])
tensor([[True, True],
        [True, True]])
tensor([[ True,  True],
        [ True, False]])
tensor([[False, False],
        [False,  True]])


#### 6. Special Functions 

In [54]:
m = torch.randint(0, 100, (4,4), dtype=torch.float32)
print("m:\n", m)

m:
 tensor([[69., 27., 70., 10.],
        [41., 84., 19., 69.],
        [ 5., 99., 72., 62.],
        [42., 71., 14., 39.]])


In [55]:
# log
torch.log(m)

tensor([[4.2341, 3.2958, 4.2485, 2.3026],
        [3.7136, 4.4308, 2.9444, 4.2341],
        [1.6094, 4.5951, 4.2767, 4.1271],
        [3.7377, 4.2627, 2.6391, 3.6636]])

In [56]:
# exp
torch.exp(m)

tensor([[9.2538e+29, 5.3205e+11, 2.5154e+30, 2.2026e+04],
        [6.3984e+17, 3.0251e+36, 1.7848e+08, 9.2538e+29],
        [1.4841e+02,        inf, 1.8587e+31, 8.4384e+26],
        [1.7393e+18, 6.8377e+30, 1.2026e+06, 8.6593e+16]])

In [57]:
# sqrt
torch.sqrt(m)

tensor([[8.3066, 5.1962, 8.3666, 3.1623],
        [6.4031, 9.1652, 4.3589, 8.3066],
        [2.2361, 9.9499, 8.4853, 7.8740],
        [6.4807, 8.4261, 3.7417, 6.2450]])

In [58]:
# sigmoid
torch.sigmoid(m)

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [0.9933, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])

In [59]:
# softmax (Columns)
torch.softmax(m, dim=0)

tensor([[1.0000e+00, 5.3802e-32, 1.1920e-01, 2.3781e-26],
        [6.9144e-13, 3.0590e-07, 8.4580e-24, 9.9909e-01],
        [1.6038e-28, 1.0000e+00, 8.8080e-01, 9.1105e-04],
        [1.8795e-12, 6.9144e-13, 5.6990e-26, 9.3491e-14]])

In [60]:
# softmax (Rows)
torch.softmax(m, dim=1)

tensor([[2.6894e-01, 1.5463e-19, 7.3106e-01, 6.4015e-27],
        [2.1151e-19, 1.0000e+00, 5.9001e-29, 3.0590e-07],
        [1.5008e-41, 1.0000e+00, 1.8795e-12, 8.5330e-17],
        [2.5437e-13, 1.0000e+00, 1.7588e-25, 1.2664e-14]])

### Inplace Operations

In [61]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print("m:\n", m)
print("n:\n", n)

m:
 tensor([[0.8119, 0.1087, 0.3943],
        [0.2973, 0.4037, 0.4018]])
n:
 tensor([[0.0513, 0.0683, 0.4218],
        [0.5065, 0.2729, 0.6883]])


In [62]:
o = m + n
print("o:\n", o)

o:
 tensor([[0.8632, 0.1770, 0.8161],
        [0.8037, 0.6766, 1.0902]])


In [63]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print("o:\n", o)

# No change in o

o:
 tensor([[0.8632, 0.1770, 0.8161],
        [0.8037, 0.6766, 1.0902]])


### Copy a Tensor

In [64]:
a = torch.tensor(range(10))
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [65]:
b = a
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [66]:
a[0] = 35
b

# I performed operation on a but b also changed. This is expected as we don't want b to take a separate space in the memory.

tensor([35,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [67]:
c = a.clone()
print(c)

tensor([35,  1,  2,  3,  4,  5,  6,  7,  8,  9])


In [68]:
a[1] = 42
print("a:\n",a)
print("b:\n",b)
print("c:\n",c)

a:
 tensor([35, 42,  2,  3,  4,  5,  6,  7,  8,  9])
b:
 tensor([35, 42,  2,  3,  4,  5,  6,  7,  8,  9])
c:
 tensor([35,  1,  2,  3,  4,  5,  6,  7,  8,  9])


### Tensors on GPU

In [69]:
torch.cuda.is_available()

True

In [70]:
device = torch.device("cuda")

In [71]:
# Creating Tensor on GPU
x = torch.rand(2,3, device=device)
print(x)

tensor([[0.3990, 0.5167, 0.0249],
        [0.9401, 0.9459, 0.7967]], device='cuda:0')


In [72]:
# CPU Tensor
a = torch.randint(-100, 100, (2,4))
print(a)

tensor([[-57,  28,  39, -18],
        [  7,  60, -12, -22]])


In [73]:
# Moving an existing tensor to GPU
b = a.to(device=device)
print(b)

tensor([[-57,  28,  39, -18],
        [  7,  60, -12, -22]], device='cuda:0')


In [74]:
# GPU Operation
b + 5

tensor([[-52,  33,  44, -13],
        [ 12,  65,  -7, -17]], device='cuda:0')

In [75]:
import time

In [76]:
# CPU vs GPU
size = 10000
mc1, mc2 = [torch.randn(size, size) for i in range(2)]
start_time = time.time()
mc = mc1@mc2
cpu_time = time.time() - start_time

In [77]:
size = 10000
mg1, mg2 = [torch.randn(size, size, device=device) for i in range(2)]
start_time = time.time()
mg = mg1@mg2
gpu_time = time.time() - start_time

In [78]:
# GPU is way faster.
cpu_time/gpu_time

37.67116739568873

### Reshaping Tensors

In [79]:
a = torch.rand((4,4), dtype=torch.float32)
print(a)

tensor([[0.6829, 0.0486, 0.3210, 0.2454],
        [0.3958, 0.2900, 0.0728, 0.4896],
        [0.4200, 0.8026, 0.1964, 0.0700],
        [0.9719, 0.1654, 0.8930, 0.5168]])


In [80]:
# Reshaping
a.reshape(2,2,2,2)

tensor([[[[0.6829, 0.0486],
          [0.3210, 0.2454]],

         [[0.3958, 0.2900],
          [0.0728, 0.4896]]],


        [[[0.4200, 0.8026],
          [0.1964, 0.0700]],

         [[0.9719, 0.1654],
          [0.8930, 0.5168]]]])

In [81]:
a.flatten()

tensor([0.6829, 0.0486, 0.3210, 0.2454, 0.3958, 0.2900, 0.0728, 0.4896, 0.4200,
        0.8026, 0.1964, 0.0700, 0.9719, 0.1654, 0.8930, 0.5168])

In [82]:
b = torch.rand(2,3,4)
b

tensor([[[0.6744, 0.1557, 0.1423, 0.9246],
         [0.8776, 0.1178, 0.5208, 0.2183],
         [0.1470, 0.5707, 0.0842, 0.3203]],

        [[0.5446, 0.9751, 0.9530, 0.8345],
         [0.8357, 0.2035, 0.9924, 0.4766],
         [0.4554, 0.9264, 0.5294, 0.2677]]])

In [83]:
# permute
print(b.permute(2, 0, 1))

print(b.permute(2, 0, 1).shape)

tensor([[[0.6744, 0.8776, 0.1470],
         [0.5446, 0.8357, 0.4554]],

        [[0.1557, 0.1178, 0.5707],
         [0.9751, 0.2035, 0.9264]],

        [[0.1423, 0.5208, 0.0842],
         [0.9530, 0.9924, 0.5294]],

        [[0.9246, 0.2183, 0.3203],
         [0.8345, 0.4766, 0.2677]]])
torch.Size([4, 2, 3])


In [84]:
# unsqueeze (Example Use case: creating image batches)

c = torch.rand(226, 226, 3)
print(c.shape)
print(c.unsqueeze(dim=0).shape)

torch.Size([226, 226, 3])
torch.Size([1, 226, 226, 3])


In [85]:
# squeeze
c.squeeze().shape

torch.Size([226, 226, 3])

### PyTorch to Numpy & Vice-Versa

In [86]:
# Tensor to Numpy Array
import numpy as np

a = torch.randint(-100, 100, (4,4), dtype=torch.float32)
print(a)
print(type(a))

print("\n")

b = a.numpy()
print(b)
print(type(b))

tensor([[ 18., -68.,  46.,  -5.],
        [  5., -74., -60.,  23.],
        [-75.,  84.,  54.,  82.],
        [ 42., -24., -74., -27.]])
<class 'torch.Tensor'>


[[ 18. -68.  46.  -5.]
 [  5. -74. -60.  23.]
 [-75.  84.  54.  82.]
 [ 42. -24. -74. -27.]]
<class 'numpy.ndarray'>


In [87]:
# Numpy Array to Tensor

c = torch.from_numpy(b)
print(c)
print(type(c))

tensor([[ 18., -68.,  46.,  -5.],
        [  5., -74., -60.,  23.],
        [-75.,  84.,  54.,  82.],
        [ 42., -24., -74., -27.]])
<class 'torch.Tensor'>
