### PyTorch Autograd is used to compute gradients during the backward pass.
Autograd is a core component of PyTorch that provides automatic differentiation for tenson operations.

In [1]:
import torch
print(torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU Exists:", torch.cuda.get_device_name())

True
GPU Exists: NVIDIA GeForce RTX 5070


In [2]:
# Examples
#1. y = x**2

In [3]:
# Requires Gradient (requires_grad) will instruct PyTorch to calculate derivative for this Tensor.

# Define x and y
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2

In [4]:
# Display x and y
x, y

(tensor(3., requires_grad=True), tensor(9., grad_fn=<PowBackward0>))

In [5]:
# Compute Gradient (dy_dx)
y.backward()

In [6]:
# Display Gradient 
x.grad

tensor(6.)

In [7]:
# A little complex example
# 2. y = x**2, z = sin(y)
import math
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
z = torch.sin(y)

In [8]:
x, y, z

(tensor(3., requires_grad=True),
 tensor(9., grad_fn=<PowBackward0>),
 tensor(0.4121, grad_fn=<SinBackward0>))

In [9]:
# Compute Gradient (dz_dz = dz_dy * dy_dx)
z.backward()

In [10]:
# Display Gradient 
x.grad

tensor(-5.4668)

In [11]:
# 3. Neural Network

x = torch.tensor(8.45)
y = torch.tensor(1.0)

print(x)
print(y)

tensor(8.4500)
tensor(1.)


In [12]:
# Parameters
w = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

print(w)
print(b)

tensor([0.0421], requires_grad=True)
tensor([0.2216], requires_grad=True)


In [13]:
# Loss Function
def loss_function(y_true, y_pred):
    return 0.5*(y_true-y_pred)**2

In [14]:
# Forward Pass
z = w * x + b
y_pred = torch.sigmoid(z)
loss = loss_function(y, y_pred)

In [15]:
print(z)
print(y_pred)
print(loss)

tensor([0.5773], grad_fn=<AddBackward0>)
tensor([0.6405], grad_fn=<SigmoidBackward0>)
tensor([0.0646], grad_fn=<MulBackward0>)


In [16]:
# Compute Gradient
loss.backward()

In [17]:
# Print Loss gradients w.r.t parameters

#d_loss_d_w
print(w.grad)

#d_loss_d_b
print(b.grad)

tensor([-0.6996])
tensor([-0.0828])


In [18]:
# How to clear gradients (To prevent accumulating gradients.)
w.grad.zero_()
w.grad

tensor([0.])

In [37]:
# Diable gradient tracking
x = torch.tensor(20.0, requires_grad=True)
x

tensor(20., requires_grad=True)

In [38]:
y = x ** 2
y

tensor(400., grad_fn=<PowBackward0>)

In [39]:
y.backward()
print(x.grad)

tensor(40.)


In [ ]:
# 3 Ways to disable gradients
# option 1 - requires_grad=False
# x.requires_grad_(False)

# option 2 - detach()
# x.detach_()

# option 3 - torch.no_grad()
# with torch.no_grad():
#     print(x)