## Pytorch Dataset & Dataloader Classes

Until now we are loading the entire dataset to train the model, this could ne inefficient if the size of data is huge as memory is limited. Also, to get better and faster convergence the batches of data work well instead of providing the entire dataset at once, which is slow and inefficient.

Dataset and DataLoader are core abstractions in PyTorch that decouple how you define your data and how you efficiently iterate over it in the training loops.

In [1]:
# Load Libraries

import torch
from torch.utils.data import Dataset, DataLoader

In [2]:
# Data -> Dataset Class -> Dataloader Class
# Dataset Class - Loading data efficiently from the disk.
# DataLoader - Creating Batches to feed to training loop.

In [3]:
# Dataset Class contains 3 methods:
# 1. Constructor (__init__()) - Which tells how data should be loaded.
# 2. Length (__len__()) - Which returns the total number of samples.
# 3. GetItem (__getitem__()) - Which returns data and label at the given index.

In [4]:
# Dataloader Class
# Shuffle -> Chunk -> Batches -> Dataset GetItem -> Collate

In [5]:
from sklearn.datasets import make_classification
import torch

In [6]:
# Create a Synthetic Classification Dataset
X, y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42
)

In [7]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [8]:
X.shape

(10, 2)

In [9]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [10]:
y.shape

(10,)

In [11]:
X = torch.from_numpy(X).to(dtype=torch.float32)
y = torch.from_numpy(y).to(dtype=torch.float32)

In [12]:

X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [13]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [14]:
from torch.utils.data import Dataset, DataLoader

In [15]:
# Dataset Class
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [16]:
dataset = CustomDataset(X, y)

In [17]:
len(dataset)

10

In [18]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [19]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0.))

In [20]:
# DataLoader Class

dataloader = DataLoader(dataset, batch_size = 2, shuffle=True)

In [21]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[ 1.7273, -1.1858],
        [ 1.0683, -0.9701]])
tensor([1., 1.])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [-1.9629, -0.9923]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]])
tensor([0., 1.])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]])
tensor([0., 1.])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.8997,  0.8344]])
tensor([0., 1.])
--------------------------------------------------
